# Generated by Django 4.1 on 2023-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empdata',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('enum', models.IntegerField()),
                ('empname', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30, null=True)),
                ('doj', models.CharField(max_length=20)),
                ('expsalary', models.IntegerField()),
                ('prevexp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
