# Generated by Django 4.1.3 on 2023-02-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_empdata_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='designation',
            field=models.CharField(max_length=130),
        ),
    ]
